Fix client not falling back to AF_INET socket connection. Check for dependencies in build scripts.

diff --git a/src/main/build b/src/main/build
--- a/src/main/build
+++ b/src/main/build
@@ -15,6 +15,17 @@ fi
 
 ## Vygeneruj kompilačné pravidlá pri prvej kompilácii.
 if [ ! -f "${MAIN_BUILD_DIR}/build.ninja" ]; then
+  ## Skontroluj závislosti.
+  ## Možno obísť manuálne ak meson nie je v $PATH lebo si pamätá odkiaľ sa volal.
+  if [ -z "$HAS_MESON" ]; then
+    echo "Missing build dependency: meson"
+    exit 1
+  fi
+  if [ -z "$HAS_NINJA" ]; then
+    echo "Missing build dependency: ninja-build"
+    exit 1
+  fi
+
   meson --buildtype release "$MAIN_ROOT_DIR" "$MAIN_BUILD_DIR"
   if [ "$?" != "0" ]; then
     exit 1
diff --git a/src/main/clean b/src/main/clean
--- a/src/main/clean
+++ b/src/main/clean
@@ -19,5 +19,10 @@ if [ ! -f "${MAIN_BUILD_DIR}/build.ninja" ]; then
   exit 1
 fi
 
+if [ -z "$HAS_NINJA" ]; then
+  echo "Missing build dependency: ninja-build"
+  exit 1
+fi
+
 ## Vymaž všetky zostavené objekty a binárky.
 ninja -C "$MAIN_BUILD_DIR" clean
